### ISSUE TITLE
Importing fails in RN 0.61.5 with: TypeError: (0 , _codegenNativeComponent.default) is not a function

### ISSUE THREAD

**Issue by etaiklein** [testing-library/native-testing-library#105]
- `react-native` or `expo`: react-native
- `native-testing-library` version: 5.0.3
- `jest-preset`: '@testing-library/react-native'
- `react-native` version: "0.61.5"
- `node` version: 8.9.4

### Relevant code or config:

see Reproduction section

### What you did:

* Tests failing after upgrade to react native 0.61.5

### What happened:

Any test file importing '@testing-library/react-native' fails

```
  ● Test suite failed to run

    TypeError: (0 , _codegenNativeComponent.default) is not a function

      1 | import ReactNative, {Image} from 'react-native';
    > 2 | import Modal from 'react-native/Libraries/Modal/Modal';
        | ^
      3 | import FormData from 'react-native/Libraries/Network/FormData';
      4 |
      5 | global.FormData = FormData;

      at Object.<anonymous> (node_modules/react-native/Libraries/Modal/RCTModalHostViewNativeComponent.js:124:17)
      at Object.<anonymous> (node_modules/react-native/Libraries/Modal/Modal.js:28:1)
      at mockComponent (node_modules/@testing-library/react-native/dist/preset/mock-component.js:26:28)
      at Object.user:/Users/etai/data/mobile/node_modules/react-native/Libraries/Modal/Modal.js: (node_modules/@testing-library/react-native/dist/preset/mock-modules.js:22:47)
      at Object.<anonymous> (member/js/__mocks__/react-native.js:2:1)
      at Object.<anonymous> (node_modules/react-native/Libraries/Utilities/codegenNativeComponent.js:16:1)
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/RefreshControl/AndroidSwipeRefreshLayoutNativeComponent.js:13:1)
      at Object.<anonymous> (node_modules/react-native/Libraries/Components/RefreshControl/RefreshControl.js:20:1)
      at mockComponent (node_modules/@testing-library/react-native/dist/preset/mock-component.js:26:28)
      at Object.user:/Users/etai/data/mobile/node_modules/react-native/Libraries/Components/RefreshControl/RefreshControl.js: (node_modules/@testing-library/react-native/dist/preset/mock-modules.js:22:47)
      at Object.require (node_modules/react-native/Libraries/Lists/VirtualizedList.js:17:24)
      at Object.require (node_modules/react-native/Libraries/Lists/FlatList.js:16:25)
      at Object.require (node_modules/react-native/Libraries/YellowBox/UI/YellowBoxList.js:14:18)
      at Object.require (node_modules/react-native/Libraries/YellowBox/YellowBox.js:50:25)
      at Object.require (node_modules/react-native/Libraries/ReactNative/AppContainer.js:137:23)
      at Object.<anonymous> (node_modules/@testing-library/react-native/dist/index.js:37:44)
      at Object.<anonymous> (member/js/steps/TodayTab.test.js:3:1)
```

### Reproduction:

This is all it takes
```js
import {render} from '@testing-library/react-native';
```

### Problem description:

Current behavior makes library unusable

### Suggested solution:

N/A

### Can you help us fix this issue by submitting a pull request?

N/A

**Comment by bcarroll22** [comment]
I just installed React Native ^0.61.5 locally and ran all of the tests of this library and they all passed, so I can't reproduce. I'm not sure what's going on, but if anyone else who is running into this could help debug it, that would be great!

**Comment by etaiklein** [comment]
I was able to solve this by mocking the modal nativeModule in my jest setup.js
```
import 'react-native/jest/setup';
import * as ReactNative from 'react-native';

jest.doMock('react-native', () => {
  return Object.setPrototypeOf(
    {
      NativeModules: {
        ...ReactNative.NativeModules,
        Override: {Modal: 'modal'},
      },
    },
    ReactNative
  );
});
```

**Comment by etaiklein** [comment]
Looks like this a jest issue from an older mock I hadn't removed when going through setup.

I solved my issue by removing this old Modal mock from `__mocks__/react-native.js`
```
- import Modal from 'react-native/Libraries/Modal/Modal';
...
- Modal.displayName = 'Modal';
- jest.setMock('react-native/Libraries/Modal/Modal', Modal);
```

My guess is that adding `preset: '@testing-library/react-native',` does some work mocking Modal already and keeping this in caused a conflict
