### ISSUE TITLE
Jest Preset @testing-library/react-native seems to not work with @expo/vector-icons

### ISSUE THREAD

**Issue by TylerSustare** [testing-library/native-testing-library#110]
- `react-native` or `expo`: **expo "~36.0.0",**
- `native-testing-library` version: **5.0.3**
- `jest-preset`: **@testing-library/react-native**
- `react-native` version: "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
- `node` version: **12.13.1**

### Relevant code or config:

```json
// package.json
{
  "dependencies": {
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-elements": "^1.2.7",
    "react-native-web": "~0.11.7"
  },
  "devDependencies": {
    "@babel/core": "^7.0.0",
    "@testing-library/react-native": "^5.0.3",
    "babel-preset-expo": "~8.0.0",
    "jest": "^25.1.0",
    "react-test-renderer": "^16.12.0"
  },
  "jest": {
    "preset": "@testing-library/react-native"
  }
}
```
``` js
// /src/Thing.js from native-testing-library example
import React from 'react';
import { StyleSheet, Text, TextInput, View } from 'react-native';
import { Button } from 'react-native-elements'; // using this to replace the 'react-native' Button breaks tests

const Thing = props => {
  const [name, setUser] = React.useState('');
  const [show, setShow] = React.useState(false);
  return (
    <View style={styles.container}>
      <TextInput value={name} onChangeText={setUser} testID="input" style={{ backgroundColor: '#fff' }} />

      <Button
        title="Print Username"
        onPress={async () => {
          setTimeout(() => {
            setShow(!show);
          }, Math.floor(Math.random() * 200));
        }}
      />
      {show && <Text testID="printed-username">{name}</Text>}
    </View>
  );
};

export default Thing;
```

``` js
// /__tests__/Thing.test.js
import React from "react";
import { fireEvent, render, wait } from "@testing-library/react-native";
import Thing from "../src/Thing";

test("examples of some things", async () => {
  const { getByTestId, getByText, queryByTestId, baseElement } = render(
    <Thing />
  );
  const famousWomanInHistory = "Ada Lovelace";

  const input = getByTestId("input");
  fireEvent.changeText(input, famousWomanInHistory);

  const button = getByText("Print Username");
  fireEvent.press(button);

  await wait(() => expect(queryByTestId("printed-username")).toBeTruthy());

  expect(getByTestId("printed-username").props.children).toBe(
    famousWomanInHistory
  );
  expect(baseElement).toMatchSnapshot();
});

```

### What you did:
I just ran `yarn test` and came across this error in my terminal
```
 FAIL  __tests__/Thing.test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/tsustare/src/projects/drinks_js/node_modules/@expo/vector-icons/Zocial.js:1
    import Zocial from './build/Zocial';
    ^^^^^^

    SyntaxError: Cannot use import statement outside a module

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:988:58)
      at Object.<anonymous> (node_modules/react-native-elements/src/helpers/getIconType.js:1:1)
```

### What happened:
Jest failed to run the test through `native-testing-library`

### Reproduction:
https://github.com/TylerSustare/preset-testing-library-react-native

Those 3 files in the relevant code section are the only changes from an `expo init <new project>`

### Problem description:
I would like to test. while using `react-native-elements` or `native-base` or other UI libraries that leverage @expo/vector-icons but I don't believe the jest preset for `@testing-libary/react-native` is handling this in a way where I can use these components in my tests.

### Suggested solution:
I started using `transformIgnorePatterns` so my package.json jest section looked like this
```json
"jest": {
    "preset": "@testing-library/react-native",
    "transformIgnorePatterns": [
      "node_modules/(?!react-native|expo|@expo/vector-icons|@unimodules)"
    ]
}
```
which resulted in this failure 
```
 FAIL  __tests__/Thing.test.js
  ● Test suite failed to run

    /Users/tsustare/src/projects/drinks_js/node_modules/@expo/vector-icons/build/vendor/react-native-vector-icons/Fonts/Zocial.ttf:1



    SyntaxError: Invalid or unexpected token

      at Runtime._execModule (node_modules/jest-runtime/build/index.js:988:58)
      at Object.<anonymous> (node_modules/@expo/vector-icons/src/Zocial.ts:2:1)

  console.warn node_modules/react-native/Libraries/YellowBox/YellowBox.js:71
    The "UMNativeModulesProxy" native module is not exported through NativeModules; verify that @unimodules/react-native-adapter's native code is linked properly

  console.warn node_modules/react-native/Libraries/YellowBox/YellowBox.js:71
    No native ExponentConstants module found, are you sure the expo-constants's module is linked properly?
```

### Can you help us fix this issue by submitting a pull request?
I can't think of what to do, but sure I'm game.

**Comment by TylerSustare** [comment]
Closing this issue, because it was my own fault, not fully understanding jest.config.* file. 
I was able to fix this issue by basically copy/pasting what is in the expo jest preset and putting it in to my jest.config.js file.

This is what my config file looks like now. 
``` js
module.exports = {
  preset: '@testing-library/react-native',
  transformIgnorePatterns: [
    'node_modules/(?!(jest-)?react-native|react-clone-referenced-element|@react-native-community|expo(nent)?|@expo(nent)?/.*|react-navigation|@react-navigation/.*|@unimodules/.*|sentry-expo|native-base|react-native-svg|vector-icons)'
  ],
  transform: {
    '^.+\\.(js|ts|tsx)$': require.resolve('react-native/jest/preprocessor.js'),
    '^.+\\.(bmp|gif|jpg|jpeg|mp4|png|psd|svg|webp|ttf|otf|m4v|mov|mp4|mpeg|mpg|webm|aac|aiff|caf|m4a|mp3|wav|html|pdf|obj)$': require.resolve(
      'jest-expo/src/preset/assetFileTransformer.js'
    )
  }
};
```
I also had to install `jest-expo` but that reason is still a mystery to me. ✨
