### ISSUE TITLE
Test failure after 0.63

### ISSUE THREAD

**Issue by mym0404** [testing-library/native-testing-library#133]
- `react-native` 
- `native-testing-library` version: 5.0.3
- `react-native` version: 0.63
- `node` version: 13.7.0

### What you did:

I upgraded RN to `0.63` and library invokes error..

### What happened:

```
 FAIL  src/providers/AuthProvider.test.tsx
  ● Test suite failed to run

    TypeError: Cannot convert undefined or null to object
        at assign (<anonymous>)

      at _extends (node_modules/@babel/runtime/helpers/extends.js:16:19)
      at node_modules/@testing-library/react-native/dist/preset/mock-modules.js:41:25
      at Object.get unstable_batchedUpdates [as unstable_batchedUpdates] (node_modules/react-native/index.js:433:12)
      at Object.<anonymous> (node_modules/react-redux/lib/utils/reactBatchedUpdates.native.js:7:48)
```

### Reproduction:

Upgrade 0.63 and run tests

**Comment by artdent** [comment]
This is a duplicate of #126

**Comment by mym0404** [comment]
Ok
