### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined for getBy*, queryBy*

### ISSUE THREAD

**Issue by abanik0831** [testing-library/native-testing-library#24]
* This bug is directly from the example given in the doc. none of the `getBy*`, `queryBy*` are working.
- `react-native`: 0.59.4
- `native-testing-library` version: 3.1.2
- `jest-preset`:
- `react-native` version: 0.59.4
- `node` version: 8.11.4

### Relevant code or config:

```js
import React from 'react';
import { Button, Text, TextInput, View } from 'react-native';
import { act, fireEvent, render, wait } from 'native-testing-library';

function Example() {
  const [name, setUser] = React.useState('');
  const [show, setShow] = React.useState(false);

  return (
    <View>
      <TextInput value={name} onChangeText={setUser} testID="input" />
      <Button
        title="Print Username"
        onPress={() => {
          // let's pretend this is making a server request, so it's async
          // (you'd want to mock this imaginary request in your unit tests)...
          setTimeout(() => {
            setShow(!show);
          }, Math.floor(Math.random() * 200));
        }}
      />
      {show && <Text testID="printed-username">{name}</Text>}
    </View>
  );
}

test('examples of some things', async () => {
  const { getByTestId, getByText, queryByTestId } = render(<Example />);
  const famousWomanInHistory = 'Ada Lovelace';

  const input = getByTestId('input');
  fireEvent.changeText(input, famousWomanInHistory);

  const button = getByText('Print Username');
  fireEvent.press(button);

  await wait(() => expect(queryByTestId('printed-username')).toBeTruthy());

  expect(getByTestId('printed-username')).toHaveTextContent(famousWomanInHistory);
  expect(rootInstance).toMatchSnapshot();
});

```

### What you did:

Ran the sample test app

### What happened:

```
● examples of some things

    TypeError: Cannot read property 'includes' of undefined

      32 |   fireEvent.changeText(input, famousWomanInHistory);
      33 | 
    > 34 |   const button = getByText('Print Username');
         |                    ^
      35 |   fireEvent.press(button);
      36 | 
      37 |   await wait(() => expect(queryByTestId('printed-username')).toBeTruthy());

      at validComponentFilter (node_modules/native-testing-library/dist/lib/query-helpers.js:37:55)
      at node_modules/native-testing-library/dist/lib/queries/text.js:32:60
      at overrideCb (node_modules/native-testing-library/dist/lib/query-helpers.js:75:22)
      at _findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:13002:11)
      at Proxy.findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12931:16)
      at Proxy.<anonymous> (node_modules/native-testing-library/dist/lib/query-helpers.js:78:24)
      at queryAllByText (node_modules/native-testing-library/dist/lib/queries/text.js:31:31)
      at node_modules/native-testing-library/dist/lib/query-helpers.js:172:24
      at node_modules/native-testing-library/dist/lib/query-helpers.js:156:24
      at _callee$ (__tests__/index.ios.js:34:20)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:271:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at tryCatch (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:40)
      at invoke (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:135:20)
      at node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:170:11
      at tryCallTwo (node_modules/promise/lib/core.js:45:5)
      at doResolve (node_modules/promise/lib/core.js:200:13)
      at new Promise (node_modules/promise/lib/core.js:66:3)
      at callInvokeWithMethodAndArg (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:169:16)
      at AsyncIterator.enqueue (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:192:7)
      at AsyncIterator.prototype.(anonymous function) [as next] (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:97:21)
      at Object.<anonymous>.exports.async (node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:216:10)
      at Object._callee (__tests__/index.ios.js:27:169)

```
### Reproduction:

Run the sample example provided in the doc

**Comment by JRasmusBm** [comment]
I am curious, I am migrating a side project from `react-native-testing-library`, and I get the same error message. I notice you closed the issue, did you happen to resolve the issue, and how did you go about it? :smile:

**Comment by bcarroll22** [comment]
Did you change the preset in your jest config?

**Comment by JRasmusBm** [comment]
@bcarroll22 Thank you for the quick reply and thank you so much for the work you are doing. I really appreciate the vision of the project and what you're doing to make the web more accessible. 

I am using Expo for that project, so my preset is `jest-expo`. Is that going to be a problem?

**Comment by bcarroll22** [comment]
You’ll want to follow [these instructions](https://www.native-testing-library.com/docs/install) to take advantage of the Expo preset and our preset.

**Comment by kgstew** [comment]
Is there a way I could conditionally set the preset for different testing files? I'm currently migrating tests from `react-test-render` to `@testing-library/react-native` and changing the preset breaks the `react-test-renderer` tests.

**Comment by bcarroll22** [comment]
@kgstew the only way I could think of would be to make your jest config file a `.js` file and set up two different npm scripts that would pass an arg that the js file could use to tell it what the preset would be. Hope that helps!

**Comment by bitttttten** [comment]
I am also hitting this issue in Expo, although `getByTestId` and `queryByTestId` work.

My package.json my jest config looks like:

```js

  "jest": {
    "preset": "jest-expo",
    "setupFiles": ["jest-expo/jest-preset.js", "@testing-library/react-native/jest-preset", "./jest/setup-mocks.js"],
    "setupFilesAfterEnv": ["./jest/setup-file.js"]
  }
```

The error I get is:

```sh
 FAIL  components/user-settings.test.tsx (27.478s)
  ● UserSettings › test

    TypeError: Cannot read property 'includes' of undefined

    > 120 |             expect(getByText("profile.sunday.button")).toHaveProp(

      at validComponentFilter (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:37:43)
      at node_modules/@testing-library/react-native/dist/lib/queries/text.js:32:47
      at overrideCb (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:75:22)
      at _findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15761:7)
      at Proxy.findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:15690:12)
      at Proxy.<anonymous> (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:78:24)
      at queryAllByText (node_modules/@testing-library/react-native/dist/lib/queries/text.js:31:31)
      at node_modules/@testing-library/react-native/dist/lib/query-helpers.js:172:24
      at getByText (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:156:24)
      at Object.<anonymous> (components/user-settings.test.tsx:120:10)
```

To fix this, I just added some more testID's and I am selecting it by then instead of the the text so it's not a blocker for me at the moment. I'll keep digging and hopefully I can work it out :)

**Comment by joseomar10** [comment]
@bitttttten I am also hitting this issue in Expo, getByTestId and queryByTestId work.

could you fix it ?

**Comment by bitttttten** [comment]
Nope! I ended up using test IDs. You could look into https://callstack.github.io/react-native-testing-library/
