### ISSUE TITLE
getByText unusable

### ISSUE THREAD

**Issue by sz-piotr** [testing-library/native-testing-library#38]
- `react-native` or `expo`: react-native
- `native-testing-library` version: 4.0.6
- `jest-preset`: react-native
- `react-native` version: 0.59.1
- `node` version: 11.4.0

### Relevant code or config:

```ts
const { getByText } = render(<SomeComponent />)
expect(getByText(/.*/).props.children).toEqual('some value')
```

### What you did:

I updated from version 2 to 4.

### What happened:

The tests failed because of the following error:
```
TypeError: Cannot read property 'includes' of undefined
      at validComponentFilter (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:37:43)
      at node_modules/@testing-library/react-native/dist/lib/queries/text.js:32:47
      at overrideCb (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:75:22)
      at _findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12981:7)
      at Proxy.findAll (node_modules/react-test-renderer/cjs/react-test-renderer.development.js:12910:12)
      at Proxy.<anonymous> (node_modules/@testing-library/react-native/dist/lib/query-helpers.js:78:24)
      at queryAllByText (node_modules/@testing-library/react-native/dist/lib/queries/text.js:31:31)
      at node_modules/@testing-library/react-native/dist/lib/query-helpers.js:172:24
      at node_modules/@testing-library/react-native/dist/lib/query-helpers.js:156:24
      at Object.<anonymous> (test/ui/ProfileAndWallet/Profile/SecurityScreen.test.ts:20:21)
```

### Problem description + Suggested solution

Calling the `getConfig` function from `validComponentFilter` given the key `"textComponents"` makes it return undefined and throw an error when attempting to call `.includes`
https://github.com/testing-library/native-testing-library/blob/master/src/lib/query-helpers.js#L24

The solution is to call configure when loading the library or permit any element to be queried if the function returns undefined

**Comment by bcarroll22** [comment]
Hello. As part of the upgrade from v2 to v4 you'll want to start using the jest preset provided by the library. Should be very straightforward, in your jest config you'll just want to change `preset: 'react-native'` to `preset: @testing-library/react-native`. This will resolve this issue for you, and shouldn't cause any new problems because our jest preset extends the react-native preset. Good luck!
